'use client'

type LeaveRecord = {
  id: string
  startDate: string
  endDate: string
  category: string
  days: number
  reason: string | null
  note: string | null
  isAutoGenerated: boolean
}

const CAT_LABEL: Record<string, string> = {
  ANNUAL: '연차',
  MONTHLY: '월차',
  HALF: '반차',
  SICK: '병가',
  PUBLIC: '공가',
  ABSENCE: '결근',
  OTHER: '기타',
}

const CAT_COLOR: Record<string, string> = {
  ANNUAL: 'bg-blue-100 text-blue-700',
  MONTHLY: 'bg-green-100 text-green-700',
  HALF: 'bg-yellow-100 text-yellow-700',
  SICK: 'bg-purple-100 text-purple-700',
  PUBLIC: 'bg-indigo-100 text-indigo-700',
  ABSENCE: 'bg-red-100 text-red-700',
  OTHER: 'bg-gray-100 text-gray-700',
}

export default function LeaveRecordTable({
  records,
  onEdit,
  onDelete,
}: {
  records: LeaveRecord[]
  onEdit: (r: LeaveRecord) => void
  onDelete: (id: string) => void
}) {
  return (
    <table className="min-w-full text-sm">
      <thead className="bg-gray-100">
        <tr>
          {['시작일', '종료일', '유형', '일수', '사유', '비고', ''].map(h => (
            <th key={h} className="px-3 py-2 text-left font-medium text-gray-600">
              {h}
            </th>
          ))}
        </tr>
      </thead>
      <tbody>
        {records.map(r => (
          <tr key={r.id} className="border-t hover:bg-gray-50">
            <td className="px-3 py-2">{new Date(r.startDate).toLocaleDateString('ko-KR')}</td>
            <td className="px-3 py-2">{new Date(r.endDate).toLocaleDateString('ko-KR')}</td>
            <td className="px-3 py-2">
              <span className={`px-2 py-0.5 rounded text-xs font-medium ${CAT_COLOR[r.category]}`}>
                {CAT_LABEL[r.category]}
              </span>
            </td>
            <td className="px-3 py-2 text-center">{r.days}</td>
            <td className="px-3 py-2 text-gray-600">{r.reason ?? '-'}</td>
            <td className="px-3 py-2 text-gray-600">{r.note ?? '-'}</td>
            <td className="px-3 py-2">
              <div className="flex gap-2 items-center">
                <button onClick={() => onEdit(r)} className="text-blue-600 hover:underline text-xs">
                  수정
                </button>
                {r.isAutoGenerated
                  ? <span className="text-xs text-gray-400">자동</span>
                  : <button onClick={() => onDelete(r.id)} className="text-red-600 hover:underline text-xs">삭제</button>
                }
              </div>
            </td>
          </tr>
        ))}
        {records.length === 0 && (
          <tr>
            <td colSpan={7} className="px-3 py-6 text-center text-gray-400">
              기록 없음
            </td>
          </tr>
        )}
      </tbody>
    </table>
  )
}
