import { NextRequest, NextResponse } from 'next/server'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/lib/auth'
import { db } from '@/lib/db'
import { calculateTardyDeduction } from '@/lib/tardy'

export async function POST(req: NextRequest, { params }: { params: { id: string } }) {
  const session = await getServerSession(authOptions)
  if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const { date, note } = await req.json()

  const employee = await db.employee.findUnique({ where: { id: params.id } })
  if (!employee) return NextResponse.json({ error: 'Not found' }, { status: 404 })

  const { deductCount, newTardyCount } = calculateTardyDeduction(employee.tardyCount)

  const tardyDate = new Date(date)

  const [updatedEmployee, tardyRecord] = await db.$transaction([
    db.employee.update({ where: { id: params.id }, data: { tardyCount: newTardyCount } }),
    db.tardyRecord.create({ data: { employeeId: params.id, date: tardyDate, note: note || null } }),
  ])

  let autoRecord = null
  if (deductCount > 0) {
    autoRecord = await db.leaveRecord.create({
      data: {
        employeeId: params.id,
        startDate: tardyDate,
        endDate: tardyDate,
        category: 'HALF',
        days: 0.5 * deductCount,
        reason: '지각 3회 차감',
        note: note || null,
        isAutoGenerated: true,
      },
    })
  }

  return NextResponse.json({
    employee: { ...updatedEmployee, tardyCount: newTardyCount },
    deducted: deductCount > 0,
    autoRecord,
    tardyRecord,
  })
}
